[package]
name = "qtrs-platform"
version = "0.1.0"
edition = "2021"

[dependencies]
qtrs-core = { path = "../qtrs-core" }
qtrs-gui = { path = "../qtrs-gui" }
bitflags = "2.4"
tinyfiledialogs = "3.9.1"

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
# Future dependencies: zbus, x11rb / wayland-client

[target.'cfg(target_os = "macos")'.dependencies]
# Future dependencies: objc2, objc2-app-kit
