[package]
name = "qtrs-widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
qtrs-core = { path = "../qtrs-core" }
qtrs-gui = { path = "../qtrs-gui" }
qtrs-platform = { path = "../qtrs-platform" }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
parking_lot = "0.12"
