// src/ui/placement.rs — where the HUD window is put on the screens.
//
// Port of the placement rules in python/ui/hud_window.py (`_restore_or_default_position`,
// `_ensure_within_screen`, and the move in `_reset_geometry`), written as pure functions over
// screen rectangles so they can be checked against the real Python functions
// (`placement_oracle.txt`, generated by rust/tools/gen_hud_placement_oracle.py).
//
// Every rectangle in the Python code is a `QRect` from `QScreen.availableGeometry()` (the work
// area: without the taskbar). `QRect::right()`/`bottom()` are the last pixel *inside*
// (`x + width - 1`), and `QRect::center()` is `(x1 + x2) / 2` on those inclusive corners
// (qrect.h:199-203,253-257). qtrs `Rect::right()`/`bottom()` are `x + width`, and
// `Rect::center()` is `x + width / 2`, so none of those are used here (Contract G11.4.e).

use qtrs_gui::geometry::primitives::Rect;

/// `QRect::right()`.
fn qt_right(r: Rect) -> i64 {
    r.x as i64 + r.width as i64 - 1
}

/// `QRect::bottom()`.
fn qt_bottom(r: Rect) -> i64 {
    r.y as i64 + r.height as i64 - 1
}

/// `QRect::center()`: integer division truncating toward zero, like C++.
fn qt_center(r: Rect) -> (i64, i64) {
    ((r.x as i64 + qt_right(r)) / 2, (r.y as i64 + qt_bottom(r)) / 2)
}

/// `QRect::contains(QPoint)` (inclusive on all four edges).
fn qt_contains(r: Rect, (px, py): (i64, i64)) -> bool {
    px >= r.x as i64 && px <= qt_right(r) && py >= r.y as i64 && py <= qt_bottom(r)
}

/// Size of `a.intersected(b)`, `(0, 0)` if they do not overlap.
fn intersection_size(a: Rect, b: Rect) -> (i64, i64) {
    let w = qt_right(a).min(qt_right(b)) - (a.x as i64).max(b.x as i64) + 1;
    let h = qt_bottom(a).min(qt_bottom(b)) - (a.y as i64).max(b.y as i64) + 1;
    if w <= 0 || h <= 0 {
        (0, 0)
    } else {
        (w, h)
    }
}

/// `_restore_or_default_position(x, y, w, h)` (hud_window.py:403-424): the saved position if the
/// window would show at least 50x30 pixels of some screen's work area there, otherwise the
/// default spot near the top right of the primary screen.
///
/// `screens` are all work areas in `QGuiApplication.screens()` order; `primary` is the primary
/// screen's work area. A saved position needs both coordinates (`x is not None and y is not None`).
pub fn restore_or_default_position(
    saved: Option<(i32, i32)>,
    w: i32,
    h: i32,
    screens: &[Rect],
    primary: Option<Rect>,
) -> (i32, i32) {
    if let Some((x, y)) = saved {
        let candidate = Rect::new(x, y, w, h);
        for &screen in screens {
            let (iw, ih) = intersection_size(screen, candidate);
            if iw >= 50 && ih >= 30 {
                return (x, y);
            }
        }
    }
    match primary {
        Some(p) => (
            (p.x as i64 + 10).max(p.x as i64 + p.width as i64 - w as i64 - 40) as i32,
            (p.y as i64 + 10).max(p.y as i64 + 50) as i32,
        ),
        None => (100, 100),
    }
}

/// `_ensure_within_screen(w, h)` (hud_window.py:376-401): keep the window inside the work area of
/// the screen holding its centre.
///
/// `geometry` is the window's position with its new size. The screen is the first one whose work
/// area contains the centre; failing that `window_screen` (`self.screen()`), failing that
/// `primary`. With no screen at all the window does not move. Returns the position to move to.
pub fn ensure_within_screen(
    geometry: Rect,
    screens: &[Rect],
    window_screen: Option<Rect>,
    primary: Option<Rect>,
) -> (i32, i32) {
    let center = qt_center(geometry);
    let target = screens
        .iter()
        .copied()
        .find(|&s| qt_contains(s, center))
        .or(window_screen)
        .or(primary);
    let Some(avail) = target else {
        return (geometry.x, geometry.y);
    };

    let (w, h) = (geometry.width as i64, geometry.height as i64);
    let (left, top) = (avail.x as i64, avail.y as i64);
    let (right, bottom) = (qt_right(avail), qt_bottom(avail));
    let (mut x, mut y) = (geometry.x as i64, geometry.y as i64);

    if x + w > right {
        x = left.max(right - w);
    }
    if x < left {
        x = left;
    }
    if y + h > bottom {
        y = top.max(bottom - h);
    }
    if y < top {
        y = top;
    }
    (x as i32, y as i32)
}

/// The position `_reset_geometry` moves to (hud_window.py:857-858): 40 px in from the right edge
/// and 50 px down from the top of the primary screen's work area. Python does not clamp it.
pub fn reset_position(w: i32, primary: Rect) -> (i32, i32) {
    (primary.x + primary.width - w - 40, primary.y + 50)
}

/// The platform's screens as work areas, for the functions above.
pub struct Screens {
    pub available: Vec<Rect>,
    full: Vec<Rect>,
    pub primary: Option<Rect>,
}

impl Screens {
    pub fn current() -> Self {
        let platform = qtrs_platform::platform();
        let screens = platform.screens();
        Self {
            available: screens.iter().map(|s| s.available_geometry()).collect(),
            full: screens.iter().map(|s| s.geometry()).collect(),
            primary: Some(platform.primary_screen().available_geometry()),
        }
    }

    /// Stand-in for `QWidget.screen()`: the work area of the screen the window overlaps most.
    /// Qt asks the platform for the window's monitor (`MonitorFromWindow`); qtrs has no
    /// `Window::screen()` yet (Contract G11.4.b), so this approximates it from the geometry.
    pub fn window_screen(&self, geometry: Rect) -> Option<Rect> {
        let mut best: Option<(i64, usize)> = None;
        for (i, &full) in self.full.iter().enumerate() {
            let (w, h) = intersection_size(full, geometry);
            let area = w * h;
            if area > 0 && best.map_or(true, |(a, _)| area > a) {
                best = Some((area, i));
            }
        }
        best.map(|(_, i)| self.available[i])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const ORACLE: &str = include_str!("placement_oracle.txt");

    fn rect(s: &str) -> Rect {
        let v: Vec<i32> = s.split(',').map(|n| n.parse().unwrap()).collect();
        Rect::new(v[0], v[1], v[2], v[3])
    }

    fn pair(s: &str) -> (i32, i32) {
        let (a, b) = s.split_once(',').unwrap();
        (a.parse().unwrap(), b.parse().unwrap())
    }

    /// `key=value` field of an oracle line.
    fn field<'a>(line: &'a str, key: &str) -> &'a str {
        let pat = format!("{key}=");
        let start = line.find(&pat).unwrap_or_else(|| panic!("no {key} in {line}")) + pat.len();
        line[start..].split(' ').next().unwrap()
    }

    fn screens_of(line: &str) -> Vec<Rect> {
        field(line, "screens").split(';').map(rect).collect()
    }

    fn pick(screens: &[Rect], idx: &str) -> Option<Rect> {
        let i: i32 = idx.parse().unwrap();
        (i >= 0).then(|| screens[i as usize])
    }

    /// The expected result of an oracle line.
    fn expected(line: &str) -> &str {
        line.split_once(" => ").unwrap().1
    }

    /// Every case below is the output of the real Python function on the same input.
    #[test]
    fn ensure_within_screen_matches_python() {
        let mut n = 0;
        let mut moved = 0;
        for line in ORACLE.lines().filter(|l| l.starts_with("E ")) {
            let screens = screens_of(line);
            let geom = rect(field(line, "geom"));
            let got = ensure_within_screen(
                geom,
                &screens,
                pick(&screens, field(line, "winscreen")),
                pick(&screens, field(line, "primary")),
            );
            assert_eq!(pair(expected(line)), got, "{line}");
            n += 1;
            moved += (got != (geom.x, geom.y)) as usize;
        }
        assert!(n > 1000, "oracle has {n} E cases");
        assert!(moved > 300, "only {moved} of {n} cases move the window: the oracle is too tame");
    }

    #[test]
    fn restore_or_default_position_matches_python() {
        let (mut n, mut defaulted, mut kept) = (0, 0, 0);
        for line in ORACLE.lines().filter(|l| l.starts_with("R ")) {
            let screens = screens_of(line);
            let saved = match field(line, "saved") {
                "none" => None,
                s => Some(pair(s)),
            };
            let (w, h) = pair(field(line, "size"));
            let got = restore_or_default_position(saved, w, h, &screens, pick(&screens, field(line, "primary")));
            assert_eq!(pair(expected(line)), got, "{line}");
            n += 1;
            match saved {
                Some(p) if p == got => kept += 1,
                _ => defaulted += 1,
            }
        }
        assert!(n > 400, "oracle has {n} R cases");
        assert!(kept > 50 && defaulted > 50, "kept {kept}, defaulted {defaulted}: oracle one-sided");
    }

    #[test]
    fn reset_position_matches_python() {
        let mut n = 0;
        for line in ORACLE.lines().filter(|l| l.starts_with("X ")) {
            let primary = rect(field(line, "primary"));
            let v: Vec<i32> = expected(line).split(',').map(|n| n.parse().unwrap()).collect();
            assert_eq!((v[2], v[3]), reset_position(v[0], primary), "{line}");
            n += 1;
        }
        assert_eq!(n, 27);
    }

    // The three Qt behaviours the port depends on, spelled out for a reader of the oracle.

    #[test]
    fn qrect_right_bottom_and_center_are_inclusive() {
        let r = Rect::new(0, 0, 1920, 1040);
        assert_eq!(qt_right(r), 1919);
        assert_eq!(qt_bottom(r), 1039);
        assert_eq!(qt_center(r), (959, 519), "(0 + 1919) / 2, not 1920 / 2");
        // Truncation toward zero for negative coordinates, as C++ `/`.
        assert_eq!(qt_center(Rect::new(-1920, 0, 1920, 100)), (-960, 49));
        assert_eq!(qt_center(Rect::new(-3, 0, 2, 1)), (-2, 0), "(-3 + -2) / 2 = -2 (trunc), not -3");
    }

    #[test]
    fn window_screen_is_the_most_overlapped_one_or_none() {
        let s = Screens {
            available: vec![Rect::new(0, 0, 1000, 760), Rect::new(1000, 0, 1000, 760)],
            full: vec![Rect::new(0, 0, 1000, 800), Rect::new(1000, 0, 1000, 800)],
            primary: Some(Rect::new(0, 0, 1000, 760)),
        };
        assert_eq!(s.window_screen(Rect::new(900, 0, 400, 300)), Some(s.available[1]));
        assert_eq!(s.window_screen(Rect::new(700, 0, 400, 300)), Some(s.available[0]));
        assert_eq!(s.window_screen(Rect::new(5000, 0, 400, 300)), None);
    }
}
